from pygame import Vector2


GAME_SCREEN: Vector2 = Vector2(800,600)
TITLE = 'Pygame - Typing Game'
SCALE = 6
SCREEN_WIDTH, SCREEN_HEIGHT = (GAME_SCREEN.x*SCALE, GAME_SCREEN.y*SCALE)
BG_COLOR = '#272744'
TEXT_COLOR = '#8b6d9c'
MENU_TEXT_COLOR = '#fbf5ef'
FPS = 20