from pygame import Vector2

TILE_SIZE = 8
GAME_SCREEN = Vector2(128,128)


TITLE = 'Pygame - Typing'
SCALE = 6
SCREEN_WIDTH, SCREEN_HEIGHT = (GAME_SCREEN.x*SCALE, GAME_SCREEN.y*SCALE)
BG_COLOR = (0, 0, 0)
FPS = 60